name: GitHub Registry :latest

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
          
      - name: Publish to github registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: exelban/gcloud/cli
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
