name: test

on: [push]

jobs:
  info-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: ./
        env:
          PROJECT_ID: ${{secrets.GCP_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        with:
          args: info

  multistep-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: ./
        env:
          PROJECT_ID: ${{secrets.GCP_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - uses: ./
        with:
          args: info